### ISSUE TITLE
Do poprawki

### ISSUE THREAD

**Issue by mjochab** [Achaj/projekt-Java#10]
Wszystko jest dość ładnie tylko jedna uwaga do poprawy. To ma być dynamiczna struktura, czyli nie zakładamy nigdzie ile może być pięter, pomieszczeń itd. 
Czyli wszelkie deklaracje przy polach typu Pietro [] pietra = new .... nie wchodzą w grę.
Co za tym idzie liczenie pola też musi być dynamicznie zrobione - nie zakładając konkretnej ilości.

**Comment by Achaj** [comment]
Poprawiono strukturę i metodę

**Comment by mjochab** [comment]
OK
